---
# Source: books/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
  labels:
    helm.sh/chart: books-0.1.0
    app.kubernetes.io/name: books
    app.kubernetes.io/instance: bookapp
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: books
      app.kubernetes.io/instance: bookapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: books
        app.kubernetes.io/instance: bookapp
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: books
          securityContext:
            {}
          image: "tntk/prod/books:temptag"
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args: ["alembic upgrade head && uvicorn books.main:app --host 0.0.0.0 --port 8000 --reload"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /books/metrics
              port: http
          readinessProbe:
            httpGet:
              path: /books/metrics
              port: http
          resources:
            {}
          volumeMounts:
          - name: bookapp-configmap
            mountPath: /code/.env
            subPath: .env
      volumes:
      - name: bookapp-configmap
        configMap:
          name: bookapp-configmap
